### ISSUE TITLE
Go modules

### ISSUE THREAD

**Issue by Zenithar** [fallais/gocoop#5]
In order to make your project GOPATh independent, you should use `go modules`.

At the root of your project

```
go mod init github.com/fallais/gocoop
```

And then globally replace all `gocoop/*` by `github.com/fallais/gocoop/`.

It allows you to handle dependencies directly bound to your project, and prevent GOPATH poisoning problem.

I can make a PR if you want.

**Comment by fallais** [comment]
Hello @Zenithar !

You're completly right, I heard about `go modules` recently and I wanted to implement them for my projects, this one included. That being said, I did not really understand the way to acheive this, I was searching for examples.

Your PR could be a great example and a very good start ! Thanks :)

**Comment by fallais** [comment]
It has been merged, thanks a lot @Zenithar !
