### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by davetom13** [fallais/gocoop#9]
I've tried multiple installs and i get the same error when i try to run gocoop. I've tried on raspberry pi 3 and odroid. I've tried docker pull and github pull. If i manually create the file it still doesnt see it. If i change the directory the error changes to the new directory. What am I doing wrong. 

gocoop             | time="2020-07-04T19:38:48+02:00" level=fatal msg="Error while reading configuration file" error="read /usr/bin/config.yml: is a directory"

**Comment by fallais** [comment]
Hello @davetom13 , can I see you `docker-compose.yml` or your `docker run` command please ?

**Comment by fallais** [comment]
Did you see my message @davetom13 ?

**Comment by fallais** [comment]
Closing this issue because I cannot investigate with further information
